-- Seed data for CivicMind demo
-- Creates realistic civic data for testing

-- Seed 311 requests (50 rows)
insert into public.requests_311 (created_at, status, type, district, lat, lng) values
  (now() - interval '1 day', 'open', 'pothole', 'Downtown', 37.7749, -122.4194),
  (now() - interval '2 days', 'open', 'pothole', 'Downtown', 37.7750, -122.4195),
  (now() - interval '3 days', 'in_progress', 'pothole', 'North', 37.7850, -122.4100),
  (now() - interval '4 days', 'closed', 'pothole', 'South', 37.7650, -122.4300),
  (now() - interval '1 day', 'open', 'waste', 'East', 37.7700, -122.4000),
  (now() - interval '2 days', 'open', 'waste', 'West', 37.7800, -122.4400),
  (now() - interval '5 days', 'closed', 'waste', 'Downtown', 37.7749, -122.4194),
  (now() - interval '1 day', 'open', 'streetlight', 'North', 37.7900, -122.4150),
  (now() - interval '3 days', 'in_progress', 'streetlight', 'South', 37.7600, -122.4350),
  (now() - interval '6 days', 'closed', 'streetlight', 'East', 37.7720, -122.4020),
  (now() - interval '1 day', 'open', 'transit_delay', 'Downtown', 37.7749, -122.4194),
  (now() - interval '2 days', 'open', 'transit_delay', 'North', 37.7880, -122.4120),
  (now() - interval '1 day', 'open', 'graffiti', 'West', 37.7820, -122.4420),
  (now() - interval '4 days', 'closed', 'graffiti', 'South', 37.7630, -122.4330),
  (now() - interval '7 days', 'closed', 'pothole', 'East', 37.7710, -122.4010),
  (now() - interval '8 days', 'closed', 'waste', 'North', 37.7870, -122.4130),
  (now() - interval '9 days', 'closed', 'streetlight', 'Downtown', 37.7749, -122.4194),
  (now() - interval '10 days', 'closed', 'transit_delay', 'West', 37.7810, -122.4410),
  (now() - interval '11 days', 'closed', 'graffiti', 'East', 37.7730, -122.4030),
  (now() - interval '12 days', 'closed', 'pothole', 'South', 37.7640, -122.4340),
  (now() - interval '2 days', 'open', 'pothole', 'Downtown', 37.7755, -122.4200),
  (now() - interval '3 days', 'open', 'waste', 'North', 37.7860, -122.4110),
  (now() - interval '4 days', 'in_progress', 'streetlight', 'East', 37.7715, -122.4015),
  (now() - interval '5 days', 'closed', 'transit_delay', 'South', 37.7645, -122.4345),
  (now() - interval '1 day', 'open', 'graffiti', 'West', 37.7815, -122.4415),
  (now() - interval '6 days', 'closed', 'pothole', 'Downtown', 37.7752, -122.4197),
  (now() - interval '7 days', 'closed', 'waste', 'North', 37.7875, -122.4125),
  (now() - interval '8 days', 'closed', 'streetlight', 'East', 37.7725, -122.4025),
  (now() - interval '9 days', 'closed', 'transit_delay', 'South', 37.7655, -122.4355),
  (now() - interval '10 days', 'closed', 'graffiti', 'West', 37.7825, -122.4425),
  (now() - interval '1 day', 'open', 'pothole', 'North', 37.7890, -122.4140),
  (now() - interval '2 days', 'open', 'waste', 'South', 37.7660, -122.4360),
  (now() - interval '3 days', 'in_progress', 'streetlight', 'Downtown', 37.7749, -122.4194),
  (now() - interval '4 days', 'closed', 'transit_delay', 'East', 37.7735, -122.4035),
  (now() - interval '5 days', 'closed', 'graffiti', 'North', 37.7885, -122.4135),
  (now() - interval '1 day', 'open', 'pothole', 'West', 37.7830, -122.4430),
  (now() - interval '2 days', 'open', 'waste', 'Downtown', 37.7749, -122.4194),
  (now() - interval '3 days', 'in_progress', 'streetlight', 'South', 37.7665, -122.4365),
  (now() - interval '4 days', 'closed', 'transit_delay', 'North', 37.7895, -122.4145),
  (now() - interval '5 days', 'closed', 'graffiti', 'East', 37.7740, -122.4040),
  (now() - interval '13 days', 'closed', 'pothole', 'Downtown', 37.7749, -122.4194),
  (now() - interval '14 days', 'closed', 'waste', 'North', 37.7865, -122.4115),
  (now() - interval '15 days', 'closed', 'streetlight', 'South', 37.7650, -122.4350),
  (now() - interval '16 days', 'closed', 'transit_delay', 'East', 37.7720, -122.4020),
  (now() - interval '17 days', 'closed', 'graffiti', 'West', 37.7820, -122.4420),
  (now() - interval '1 day', 'open', 'pothole', 'South', 37.7670, -122.4370),
  (now() - interval '2 days', 'open', 'waste', 'East', 37.7745, -122.4045),
  (now() - interval '3 days', 'in_progress', 'streetlight', 'West', 37.7835, -122.4435),
  (now() - interval '4 days', 'closed', 'transit_delay', 'Downtown', 37.7749, -122.4194),
  (now() - interval '5 days', 'closed', 'graffiti', 'North', 37.7900, -122.4150);

-- Seed budget data (20 rows)
insert into public.budget (fiscal_year, department, amount_usd) values
  (2024, 'Education', 450000000),
  (2024, 'Public Safety', 380000000),
  (2024, 'Sanitation', 120000000),
  (2024, 'Parks', 85000000),
  (2024, 'Transportation', 210000000),
  (2024, 'Health Services', 165000000),
  (2024, 'Housing', 95000000),
  (2024, 'Economic Development', 55000000),
  (2024, 'City Administration', 75000000),
  (2024, 'Technology', 45000000),
  (2025, 'Education', 475000000),
  (2025, 'Public Safety', 395000000),
  (2025, 'Sanitation', 125000000),
  (2025, 'Parks', 90000000),
  (2025, 'Transportation', 225000000),
  (2025, 'Health Services', 175000000),
  (2025, 'Housing', 105000000),
  (2025, 'Economic Development', 60000000),
  (2025, 'City Administration', 78000000),
  (2025, 'Technology', 52000000);

-- Seed events (30 rows)
insert into public.events (date, title, category, district) values
  (current_date + interval '1 day', 'City Council Meeting', 'council_meeting', 'Downtown'),
  (current_date + interval '2 days', 'Public Hearing: Zoning Changes', 'public_hearing', 'North'),
  (current_date + interval '3 days', 'Community Cleanup Drive', 'cleanup_drive', 'South'),
  (current_date + interval '4 days', 'Budget Review Session', 'council_meeting', 'Downtown'),
  (current_date + interval '5 days', 'Park Renovation Public Input', 'public_hearing', 'East'),
  (current_date + interval '6 days', 'Neighborhood Watch Meeting', 'council_meeting', 'West'),
  (current_date + interval '7 days', 'Transit Expansion Hearing', 'public_hearing', 'Downtown'),
  (current_date + interval '8 days', 'River Cleanup Event', 'cleanup_drive', 'North'),
  (current_date + interval '9 days', 'City Planning Commission', 'council_meeting', 'Downtown'),
  (current_date + interval '10 days', 'Housing Policy Forum', 'public_hearing', 'South'),
  (current_date + interval '11 days', 'Street Tree Planting', 'cleanup_drive', 'East'),
  (current_date + interval '12 days', 'Public Safety Town Hall', 'public_hearing', 'West'),
  (current_date + interval '13 days', 'City Council Meeting', 'council_meeting', 'Downtown'),
  (current_date + interval '14 days', 'Bike Lane Proposal Hearing', 'public_hearing', 'North'),
  (current_date + interval '15 days', 'Beach Cleanup Day', 'cleanup_drive', 'South'),
  (current_date - interval '1 day', 'Past City Council Meeting', 'council_meeting', 'Downtown'),
  (current_date - interval '2 days', 'Past Public Hearing', 'public_hearing', 'East'),
  (current_date - interval '3 days', 'Past Cleanup Drive', 'cleanup_drive', 'West'),
  (current_date - interval '7 days', 'Last Week Council Meeting', 'council_meeting', 'Downtown'),
  (current_date - interval '8 days', 'Last Week Public Hearing', 'public_hearing', 'North'),
  (current_date + interval '16 days', 'Education Budget Workshop', 'council_meeting', 'Downtown'),
  (current_date + interval '17 days', 'Affordable Housing Hearing', 'public_hearing', 'South'),
  (current_date + interval '18 days', 'Park Cleanup Saturday', 'cleanup_drive', 'East'),
  (current_date + interval '19 days', 'Traffic Safety Forum', 'public_hearing', 'West'),
  (current_date + interval '20 days', 'City Council Meeting', 'council_meeting', 'Downtown'),
  (current_date + interval '21 days', 'Climate Action Plan Hearing', 'public_hearing', 'North'),
  (current_date + interval '22 days', 'Graffiti Removal Day', 'cleanup_drive', 'South'),
  (current_date + interval '23 days', 'Small Business Forum', 'public_hearing', 'East'),
  (current_date + interval '24 days', 'Emergency Preparedness Meeting', 'council_meeting', 'West'),
  (current_date + interval '25 days', 'Waterfront Development Hearing', 'public_hearing', 'Downtown');

-- Seed citizen feedback (40 rows)
insert into public.citizen_feedback (created_at, text, district, sentiment, score) values
  (now() - interval '1 day', 'The new bike lanes are fantastic!', 'Downtown', 'positive', 0.85),
  (now() - interval '1 day', 'Buses are late every evening on 5th Ave', 'North', 'negative', -0.66),
  (now() - interval '2 days', 'Love the new park renovations', 'South', 'positive', 0.92),
  (now() - interval '2 days', 'Potholes on Main St need urgent attention', 'East', 'negative', -0.75),
  (now() - interval '3 days', 'City services are improving', 'West', 'positive', 0.70),
  (now() - interval '3 days', 'Trash pickup was missed again this week', 'Downtown', 'negative', -0.60),
  (now() - interval '4 days', 'Great job on the community center', 'North', 'positive', 0.88),
  (now() - interval '4 days', 'Street lights are out on Oak Avenue', 'South', 'negative', -0.55),
  (now() - interval '5 days', 'The city website is much easier to use now', 'East', 'positive', 0.78),
  (now() - interval '5 days', 'Need more parking downtown', 'West', 'negative', -0.45),
  (now() - interval '6 days', 'Public library hours are perfect', 'Downtown', 'positive', 0.82),
  (now() - interval '6 days', 'Graffiti problem getting worse', 'North', 'negative', -0.70),
  (now() - interval '7 days', 'Appreciate the quick response to my 311 request', 'South', 'positive', 0.90),
  (now() - interval '7 days', 'Construction noise is unbearable', 'East', 'negative', -0.80),
  (now() - interval '8 days', 'New playground equipment is excellent', 'West', 'positive', 0.95),
  (now() - interval '8 days', 'Water pressure issues in my neighborhood', 'Downtown', 'negative', -0.50),
  (now() - interval '9 days', 'City events are well organized', 'North', 'positive', 0.75),
  (now() - interval '9 days', 'Sidewalks need repair', 'South', 'negative', -0.58),
  (now() - interval '10 days', 'Love the farmers market', 'East', 'positive', 0.87),
  (now() - interval '10 days', 'Traffic congestion is terrible', 'West', 'negative', -0.72),
  (now() - interval '11 days', 'Parks are clean and well maintained', 'Downtown', 'positive', 0.83),
  (now() - interval '11 days', 'Need better public transit options', 'North', 'negative', -0.62),
  (now() - interval '12 days', 'City staff are very helpful', 'South', 'positive', 0.80),
  (now() - interval '12 days', 'Recycling program is confusing', 'East', 'negative', -0.48),
  (now() - interval '13 days', 'Community events bring us together', 'West', 'positive', 0.89),
  (now() - interval '13 days', 'Noise complaints not being addressed', 'Downtown', 'negative', -0.65),
  (now() - interval '14 days', 'New crosswalks make streets safer', 'North', 'positive', 0.86),
  (now() - interval '1 day', 'The response time for emergencies is good', 'South', 'positive', 0.77),
  (now() - interval '2 days', 'More bike racks needed downtown', 'East', 'neutral', 0.15),
  (now() - interval '3 days', 'City budget priorities seem reasonable', 'West', 'neutral', 0.20),
  (now() - interval '4 days', 'Public art installations are inspiring', 'Downtown', 'positive', 0.91),
  (now() - interval '5 days', 'Snow removal could be faster', 'North', 'negative', -0.52),
  (now() - interval '6 days', 'Community center programs are diverse', 'South', 'positive', 0.84),
  (now() - interval '7 days', 'Permit process takes too long', 'East', 'negative', -0.68),
  (now() - interval '8 days', 'Love the new dog park', 'West', 'positive', 0.93),
  (now() - interval '9 days', 'Street sweeping schedule is inconvenient', 'Downtown', 'negative', -0.42),
  (now() - interval '10 days', 'City transparency has improved', 'North', 'positive', 0.76),
  (now() - interval '11 days', 'Need more affordable housing', 'South', 'negative', -0.78),
  (now() - interval '12 days', 'Public wifi in parks is great', 'East', 'positive', 0.81),
  (now() - interval '13 days', 'Zoning changes are concerning', 'West', 'negative', -0.55);
